# Generated by Django 5.2.17 on 2026-08-28 08:20

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HWCIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('description', models.TextField()),
                ('animal_count', models.PositiveSmallIntegerField(default=1)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=12)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('event_time', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=12)),
                ('property_damage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='communities.community')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='communities.wildlifespecies')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='CRITICAL', max_length=12)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='incidents.hwcincident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident-evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'mp4'])])),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='incidents.hwcincident')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReporterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('alternate_contact', models.CharField(blank=True, max_length=160)),
                ('consent_to_contact', models.BooleanField(default=False)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_reporter_details', to='incidents.hwcincident')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('new_status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.hwcincident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='incidents.alert')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=12)),
                ('reasons', models.JSONField(default=list)),
                ('rules_version', models.CharField(default='v1', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='incidents.hwcincident')),
            ],
        ),
        migrations.AddIndex(
            model_name='hwcincident',
            index=models.Index(fields=['status', 'risk_level'], name='incidents_h_status_e8470a_idx'),
        ),
        migrations.AddIndex(
            model_name='hwcincident',
            index=models.Index(fields=['-created_at'], name='incidents_h_created_540643_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('incident', 'priority'), name='unique_incident_alert_priority'),
        ),
    ]
