# Generated by Django 5.2.17 on 2026-08-28 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RangerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('responding_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=160)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranger_response', to='incidents.hwcincident')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranger_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
